---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: nxos
namespace: cisco
readme: README.md
repository: https://github.com/ansible-collections/nxos
tags: [cisco, nxos, networking, nxapi, netconf]
