---
name: "CI"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-tox-matrix-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: NilashishC/ansible-content-actions/.github/actions/generate-tox-ansible-matrix@actions_refactor  # yamllint disable-line rule:line-length
        id: build-matrix-unit
        with:
          scope: unit
    outputs:
      envlist: "${{ steps.build-matrix-unit.outputs.envlist }}"
  run-unit-galaxy:
    needs: build-tox-matrix-unit
    strategy:
      fail-fast: false
      matrix:
        entry: "${{ fromJson(needs.build-tox-matrix-unit.outputs.envlist) }}"
    name: "${{ matrix.entry.name }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: NilashishC/ansible-content-actions/.github/actions/run-unit-galaxy@actions_refactor  # yamllint disable-line rule:line-length
        with:
          test-env: "${{ matrix.entry.name }}"

  build-tox-matrix-sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: NilashishC/ansible-content-actions/.github/actions/generate-tox-ansible-matrix@actions_refactor  # yamllint disable-line rule:line-length
        id: build-matrix-sanity
        with:
          scope: sanity
    outputs:
      envlist: "${{ steps.build-matrix-sanity.outputs.envlist }}"
  run-sanity:
    needs: build-tox-matrix-sanity
    strategy:
      fail-fast: false
      matrix:
        entry: "${{ fromJson(needs.build-tox-matrix-sanity.outputs.envlist) }}"
    name: "${{ matrix.entry.name }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: NilashishC/ansible-content-actions/.github/actions/run-sanity@actions_refactor  # yamllint disable-line rule:line-length
        with:
          test-env: "${{ matrix.entry.name }}"
